# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\tstreaming\"5\n\tDataChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\"=\n\x0eServerResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1a\n\x12processed_sequence\x18\x02 \x01(\x05\x32\x61\n\x15\x44\x61taProcessingService\x12H\n\x11ProcessDataStream\x12\x14.streaming.DataChunk\x1a\x19.streaming.ServerResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATACHUNK']._serialized_start=30
  _globals['_DATACHUNK']._serialized_end=83
  _globals['_SERVERRESPONSE']._serialized_start=85
  _globals['_SERVERRESPONSE']._serialized_end=146
  _globals['_DATAPROCESSINGSERVICE']._serialized_start=148
  _globals['_DATAPROCESSINGSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
