# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streaming_pb2 as streaming__pb2


class DataProcessingServiceStub(object):
    """Service definition with bidirectional streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDataStream = channel.stream_stream(
                '/streaming.DataProcessingService/ProcessDataStream',
                request_serializer=streaming__pb2.DataChunk.SerializeToString,
                response_deserializer=streaming__pb2.ServerResponse.FromString,
                )


class DataProcessingServiceServicer(object):
    """Service definition with bidirectional streaming
    """

    def ProcessDataStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDataStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessDataStream,
                    request_deserializer=streaming__pb2.DataChunk.FromString,
                    response_serializer=streaming__pb2.ServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.DataProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataProcessingService(object):
    """Service definition with bidirectional streaming
    """

    @staticmethod
    def ProcessDataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/streaming.DataProcessingService/ProcessDataStream',
            streaming__pb2.DataChunk.SerializeToString,
            streaming__pb2.ServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
